# Generated by Django 5.1.2 on 2024-10-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_habit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='frequency',
            field=models.TextField(default='default_category', max_length=255),
        ),
    ]
