# Generated by Django 5.1.2 on 2024-10-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserApp',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
