# Generated by Django 5.1.2 on 2024-10-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
