export const ACTION_TYPE = {
  LOGIN: "LOGIN",
  LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
  LOGIN_FAILED: "LOGIN_FAILED",
  SIGNUP: "SIGNUP",
  SIGNUP_SUCCEEDED: "SIGNUP_SUCCEEDED",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  LOGOUT: "LOGOUT",
};
